[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[build.processing.css]
  minify = true

[build.processing.js]
  minify = true

[functions]
  node_bundler = "esbuild"
  region = "eu-west-1"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/og-image.png"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"
